export const DEFAULT_PLANS = [
  {
    id: 'starter',
    name: 'Starter',
    description: 'Teste l\'app gratuitement, sans engagement.',
    price_monthly: 0,
    price_annual: 0,
    discount_annual_pct: 0,
    featured: false,
    visible: true,
    cta_label: 'Commencer gratuitement',
    features: [
      '1 objectif actif',
      '1 génération de programme',
      'Importation de séances illimitée',
      'Recommandations optimisant la progression',
      'Suivi de séances (poids, reps, repos)',
      'Accès tableau de bord',
    ],
  },
  {
    id: 'coach',
    name: 'Coach',
    description: 'L\'essentiel pour progresser sérieusement.',
    price_monthly: 9.90,
    price_annual: 6.90,
    discount_annual_pct: 30,
    featured: true,
    visible: true,
    cta_label: 'Choisir Coach',
    features: [
      "Jusqu'à 3 objectifs",
      'Génération de programme illimitée',
      'Ajustements IA après chaque séance',
      'Suivi des douleurs jusqu\'à disparition',
      // « Bilans automatiques » retiré le 2026-08-22 : rien ne les génère
      // (`ai_reviews` n'était jamais écrit) et il a été décidé de ne pas les
      // construire — le coach rédige un bilan à la demande, dans le chat.
      'Historique complet',
      'Interactions avec le coach IA débloquées',
    ],
  },
  {
    id: 'elite',
    name: 'Elite',
    description: 'L\'optimisation maximale pour gagner du temps.',
    price_monthly: 19.90,
    price_annual: 14.90,
    discount_annual_pct: 25,
    featured: false,
    visible: true,
    cta_label: 'Choisir Elite',
    features: [
      'Tout le plan Coach',
      'Mémoire IA long terme',
      'Techniques avancées (drop sets, rest-pause…)',
      'Analytics poussés & graphiques',
      'Export PDF de programme',
      "Limite d'utilisation du coach plus élevée",
    ],
  },
];