import React, { useState, useEffect } from 'react';
import { base44 } from '@/api/base44Client';
import { useQuery, useMutation, useQueryClient } from '@tanstack/react-query';
import { Card } from '@/components/ui/card';
import { Button } from '@/components/ui/button';
import { Badge } from '@/components/ui/badge';
import { Tabs, TabsContent, TabsList, TabsTrigger } from '@/components/ui/tabs';
import { Sparkles, Loader2, Calendar, Dumbbell, Clock, ChevronRight, Bookmark, BookmarkCheck, Trash2, RefreshCw } from 'lucide-react';
import { AlertDialog, AlertDialogAction, AlertDialogCancel, AlertDialogContent, AlertDialogDescription, AlertDialogFooter, AlertDialogHeader, AlertDialogTitle, AlertDialogTrigger } from '@/components/ui/alert-dialog';
import { format, addDays, startOfWeek } from 'date-fns';
import { useSearchParams } from 'react-router-dom';
import { fr } from 'date-fns/locale';
import { Link } from 'react-router-dom';
import { useRef } from 'react';
import { motion } from 'framer-motion';
import GenerateProgramDialog from '@/components/program/GenerateProgramDialog';
import { buildProgramContext, formatProgramBrief } from '@/lib/program-builder';
import { getContextualKnowledge } from '@/lib/scientific-knowledge-base';
import { normalizeUser } from '@/lib/utils';

function LoadingOrb() {
  return (
    <div className="relative flex items-center justify-center w-24 h-24">
      <style>{`
        @keyframes ping1 { 0%, 100% { transform: scale(1); opacity: 0.6; } 50% { transform: scale(1.35); opacity: 0; } }
        @keyframes ping2 { 0%, 100% { transform: scale(1); opacity: 0.4; } 50% { transform: scale(1.6); opacity: 0; } }
        @keyframes spin-slow { from { transform: rotate(0deg); } to { transform: rotate(360deg); } }
        @keyframes spin-reverse { from { transform: rotate(0deg); } to { transform: rotate(-360deg); } }
        .ring1 { animation: ping1 1.6s ease-in-out infinite; }
        .ring2 { animation: ping2 2.2s ease-in-out infinite 0.4s; }
        .arc1 { animation: spin-slow 3s linear infinite; }
        .arc2 { animation: spin-reverse 2s linear infinite; }
      `}</style>
      {/* Pulsing rings */}
      <div className="ring1 absolute inset-0 rounded-full border-2 border-white/40" />
      <div className="ring2 absolute inset-0 rounded-full border border-white/20" />
      {/* Spinning arcs */}
      <div className="arc1 absolute inset-2">
        <svg viewBox="0 0 60 60" fill="none" className="w-full h-full">
          <circle cx="30" cy="30" r="28" stroke="white" strokeOpacity="0.6" strokeWidth="2" strokeDasharray="44 132" strokeLinecap="round" />
        </svg>
      </div>
      <div className="arc2 absolute inset-4">
        <svg viewBox="0 0 40 40" fill="none" className="w-full h-full">
          <circle cx="20" cy="20" r="18" stroke="white" strokeOpacity="0.4" strokeWidth="2" strokeDasharray="28 84" strokeLinecap="round" />
        </svg>
      </div>
      {/* Center icon */}
      <div className="relative z-10 w-10 h-10 rounded-full bg-white/20 backdrop-blur flex items-center justify-center">
        <Sparkles className="w-5 h-5 text-white" />
      </div>
    </div>
  );
}

const TYPE_LABELS = { strength: 'Force', hypertrophy: 'Hypertrophie', endurance: 'Endurance', mixed: 'Mixte', full_body: 'Corps entier', upper_lower: 'Haut/Bas', ppl: 'Pousser/Tirer/Jambes', arnold_split: 'Split Arnold', custom: 'Personnalisé' };
const TYPE_COLORS = { strength: 'bg-chart-5/10 text-chart-5', hypertrophy: 'bg-primary/10 text-primary', endurance: 'bg-accent/10 text-accent', mixed: 'bg-chart-4/10 text-chart-4' };

export default function Program() {
  const queryClient = useQueryClient();
  const [searchParams] = useSearchParams();
  const [user, setUser] = useState(null);
  const [generating, setGenerating] = useState(false);
  const [genPhase, setGenPhase] = useState('');
  const [genSeconds, setGenSeconds] = useState(0);
  const genTimerRef = React.useRef(null);
  const [showDialog, setShowDialog] = useState(false);
  const [showRegenGate, setShowRegenGate] = useState(false);
  const [saving, setSaving] = useState(false);
  const [saved, setSaved] = useState(false);
  const [staleBanner, setStaleBanner] = useState(() => {
    try {
      const p = JSON.parse(localStorage.getItem('pending_program_regen') || 'null');
      return p && Date.now() - p.timestamp < 30 * 24 * 60 * 60 * 1000; // 30 jours max
    } catch { return false; }
  });
  const autoGenerated = useRef(false);

  useEffect(() => {
    base44.auth.me().then(u => setUser(normalizeUser(u)));
  }, []);

  const { data: objectives = [] } = useQuery({
    queryKey: ['objectives'],
    queryFn: () => base44.entities.Objective.filter({ status: 'active' }),
    enabled: !!user,
  });

  const { data: programs = [] } = useQuery({
    queryKey: ['programs'],
    queryFn: () => base44.entities.Program.filter({ status: 'active' }, '-created_date', 1),
    enabled: !!user,
  });

  const activeProgram = programs[0] || null;
  const alreadySaved = activeProgram ? localStorage.getItem(`saved_program_${activeProgram.id}`) === 'true' : false;

  const { data: sessions = [] } = useQuery({
    queryKey: ['program-sessions', activeProgram?.id],
    queryFn: () => base44.entities.Session.filter({ program_id: activeProgram.id }, 'planned_date'),
    enabled: !!activeProgram,
  });

  // Auto-génération après onboarding
  useEffect(() => {
    if (user && objectives.length > 0 && !activeProgram && !generating && !autoGenerated.current && searchParams.get('autoGenerate') === 'true') {
      autoGenerated.current = true;
      try {
        const ctx = buildProgramContext(user, objectives);
        generateProgram({ structure: ctx.structure, weeks: ctx.plannedWeeks, phase: 'MEV' });
      } catch (err) {
        console.error('[auto-generate] erreur :', err);
        alert(`Erreur génération automatique : ${err?.message || err}`);
      }
    }
  }, [user, objectives, activeProgram, generating]);

  const generateProgram = async ({ structure, weeks, phase }) => {
    setGenerating(true);
    setGenSeconds(0);
    setGenPhase('Analyse du profil…');
    genTimerRef.current = setInterval(() => setGenSeconds(s => s + 1), 1000);
    try {

    // Calcul intelligent des semaines si "auto" (RP — Israetel et al.)
    // MEV = départ de cycle → durée = cycle complet selon niveau
    // MAV = phase principale, 2-4 sem. de travail productif
    // MRV = pic de volume, 2-3 sem. max avant surentraînement
    if (!weeks || weeks === 'auto') {
      const level = user?.level || 'beginner';
      const resolvedPhase = phase || 'auto';
      const OPTIMAL_WEEKS = {
        //              cycle auto  MEV   MAV   MRV
        beginner:     { auto: 4,  MEV: 4, MAV: 4, MRV: 2 },
        intermediate: { auto: 6,  MEV: 6, MAV: 5, MRV: 3 },
        advanced:     { auto: 10, MEV: 10, MAV: 6, MRV: 3 },
      };
      weeks = (OPTIMAL_WEEKS[level] || OPTIMAL_WEEKS.beginner)[resolvedPhase] || 4;
    }

    // Pré-calcul déterministe — zéro API
    setGenPhase('Calcul du volume et des splits…');
    const programCtx     = buildProgramContext(user, objectives);
    const programBrief   = formatProgramBrief({ ...programCtx, structure: structure || programCtx.structure, plannedWeeks: weeks, phase });
    const scienceContext = getContextualKnowledge(user, objectives);
    setGenPhase('L\'IA construit ton programme…');

    const structureInstruction = structure
      ? `Utilise OBLIGATOIREMENT la structure "${structure}" pour organiser les séances.`
      : `Choisis la structure la plus adaptée (full_body, upper_lower, ppl, arnold_split, custom) selon le profil et le nombre de jours disponibles.`;

    const phaseInstruction = phase
      ? `Phase de départ imposée : ${phase}.`
      : `Phase de départ : MEV pour tous les niveaux en début de nouveau mésocycle (principe RP — on commence toujours au volume minimum efficace et on progresse vers le MRV sur 6-10 semaines). Exception : MAV si l'utilisateur est intermédiaire/avancé et reprend un programme déjà établi sans coupure.`;

    const prompt = `Tu es un coach sportif expert en périodisation scientifique. Ta mission : lire d'abord le profil complet, puis appliquer les références scientifiques sélectionnées POUR CE PROFIL, puis respecter le brief chiffré, puis générer.

═══════════════════════════════════════════════════
ÉTAPE 1 — PROFIL COMPLET (lire en premier, tout prendre en compte)
═══════════════════════════════════════════════════
- Niveau : ${user.level || '?'} | Âge : ${user.age || '?'} | Poids : ${user.weight || '?'}kg | Taille : ${user.height || '?'}cm | Genre : ${user.gender || '?'}
${(user.level === 'intermediate' || user.level === 'advanced') ? `- Morphologie : bras ${user.morphology_arm_length || 'moyen'}, jambes ${user.morphology_leg_length || 'moyen'}, silhouette ${user.morphology_silhouette || 'non renseignée'}, posture ${user.morphology_posture || 'non renseignée'}` : '- Morphologie : non applicable (débutant — la morphologie n\'influence pas la sélection d\'exercices à ce stade)'}
- Objectifs : ${JSON.stringify(objectives.map(o => ({ type: o.type, zone: o.zone, focus: o.focus_group, muscles: o.focus_muscles, priority: o.priority })))}
- Peaking activé (pic de performance à court terme) : ${user.peaking_enabled ? 'OUI — réduire volume, augmenter intensité pour réalisation' : 'non'}
- Disponibilités : ${user.availability_optimal ? 'FLEXIBLE — choisis les jours optimaux selon la science' : `Jours : ${(user.available_days || []).join(', ')} | Durées : ${JSON.stringify(user.duration_per_day || {})} min | Fréquence souhaitée : ${user.frequency_min || '?'}–${user.frequency_max || '?'} séances/sem`}
- Équipement STRICT (aucun autre matériel autorisé) : ${(user.equipment || []).join(', ') || 'poids du corps uniquement'}
- Exercices aimés (à prioriser) : ${(user.preferred_exercises||[]).join(', ') || 'aucun'}
- Exercices à éviter (ne jamais inclure) : ${(user.disliked_exercises||[]).join(', ') || 'aucun'}
- Muscles à NE PAS développer : ${(() => { try { const m = JSON.parse(user.no_volume_muscles || '[]'); return m.length ? m.join(', ') : 'aucun'; } catch { return user.no_volume_muscles || 'aucun'; } })()}
- Zones fragiles (adapter les exercices selon les règles scientifiques ci-dessous) : ${(() => { try { const fz = Array.isArray(user.fragile_zones) ? user.fragile_zones : JSON.parse(user.fragile_zones || '[]'); return fz.map(z => typeof z === 'string' ? z : z.key).join(', ') || 'aucune'; } catch { return 'aucune'; } })()}
- Techniques avancées autorisées : ${user.accepts_advanced_techniques ? 'oui' : 'non'}
- Préférence volume : ${['Faible (MEV)', 'Modéré (MAV)', 'Élevé (MRV)'][((user.pref_volume || 2) - 1)]}
- Préférence intensité : ${['Confort (RIR 3+)', 'Challenge (RIR 1-2)', 'Maximal (RIR 0-1)'][((user.pref_intensity || 2) - 1)]}
- Préférence fréquence : ${['1×/sem par muscle', '2×/sem par muscle', '3×+/sem par muscle'][((user.pref_frequency || 2) - 1)]}

═══════════════════════════════════════════════════
ÉTAPE 2 — RÉFÉRENCES SCIENTIFIQUES POUR CE PROFIL (applique chacune)
Ces données ont été sélectionnées spécifiquement pour le niveau, les objectifs, les zones fragiles et les contraintes du profil ci-dessus (équipement, disponibilités, préférences). Applique-les en tenant compte de ces contraintes :
═══════════════════════════════════════════════════
${scienceContext || 'Principes RP/Israetel : MEV→MAV→MRV, fréquence 2×/sem par muscle, double progression, RIR 1-3.'}

═══════════════════════════════════════════════════
ÉTAPE 3 — BRIEF PRÉ-CALCULÉ (valeurs déterministes — respecter exactement)
═══════════════════════════════════════════════════
${programBrief}

═══════════════════════════════════════════════════
ÉTAPE 4 — GÉNÉRATION
═══════════════════════════════════════════════════
${structureInstruction}
${phaseInstruction}
Génère un programme COMPLET de ${weeks} semaines.
⚠️ VOLUME SÉANCES OBLIGATOIRE : ${weeks * 3} à ${weeks * 5} séances au total (${weeks} semaines × 3-5 séances/sem selon niveau et science). Ne génère JAMAIS une seule séance sur tout le programme.
Chaque séance = tous les exercices avec sets, reps, RIR, repos.
Règles absolues : jamais à l'échec sur squat/deadlift/bench barre/OHP barre. Échec autorisé dernière série isolation uniquement. SRA : 48h min entre séances hypertrophie même muscle, 72h pour force composé lourd.

IMPORTANT FORMAT: Le champ "day" doit OBLIGATOIREMENT être en anglais minuscule parmi: monday, tuesday, wednesday, thursday, friday, saturday, sunday. Ne jamais utiliser de majuscules ou de noms français.
IMPORTANT LANGUE: Les noms des exercices ET les labels de séance (day_label) doivent être en FRANÇAIS. Exemple de day_label : "Lundi - Poitrine & Dos", "Mercredi - Jambes", "Vendredi - Full Body". Ne jamais mettre de jours en anglais dans day_label.
Les noms des exercices doivent aussi être en FRANÇAIS.
Les groupes musculaires (muscle_group) doivent aussi être en FRANÇAIS. Exemples : "Pectoraux", "Dos", "Biceps", "Triceps", "Épaules", "Jambes", "Quadriceps", "Ischio-jambiers", "Fessiers", "Abdominaux", "Mollets". Ne jamais utiliser de termes anglais comme "Chest", "Back", "Legs", etc.`;

    const result = await base44.integrations.Core.InvokeLLM({
      prompt,
      response_json_schema: {
        type: "object",
        properties: {
          weekly_structure: { type: "string" },
          multi_objective_mode: { type: "string" },
          sessions: {
          type: "array",
          items: {
          type: "object",
          properties: {
          week: { type: "number" },
          day: { type: "string", description: "Day in English lowercase: monday, tuesday, wednesday, thursday, friday, saturday, sunday" },
                day_label: { type: "string" },
                type: { type: "string" },
                estimated_duration: { type: "number" },
                active_zones: { type: "array", items: { type: "object", properties: { muscle_group: { type: "string" }, objective: { type: "string" } } } },
                exercises: { type: "array", items: { type: "object", properties: { name: { type: "string" }, muscle_group: { type: "string" }, sets: { type: "number" }, target_reps: { type: "string" }, rest_seconds: { type: "number" }, block: { type: "string" }, notes: { type: "string" } } } }
              }
            }
          }
        }
      }
    });

    // Create program
    setGenPhase('Enregistrement du programme…');
    const program = await base44.entities.Program.create({
      user_id: user.id,
      version: 1,
      objective_ids: objectives.map(o => o.id),
      weekly_structure: (() => {
        const allowed = ['full_body', 'upper_lower', 'ppl', 'arnold_split', 'phul', 'ul_ppl', 'custom'];
        const raw = structure || result.weekly_structure || 'full_body';
        return allowed.includes(raw) ? raw : 'full_body';
      })(),
      active_days: (user.available_days || []).map(d => ({ day: d, duration_minutes: (user.duration_per_day || {})[d] || 60 })),
      planned_weeks: weeks,
      active_phase: phase || 'MEV',
      status: 'active',
      multi_objective_mode: ['simple', 'parallel', 'sequential', 'vif'].includes(result.multi_objective_mode) ? result.multi_objective_mode : 'simple',
      program_data: result,
    });

    // Create sessions
    const monday = startOfWeek(new Date(), { weekStartsOn: 1 });
    const dayMap = {
      monday: 0, lundi: 0,
      tuesday: 1, mardi: 1,
      wednesday: 2, mercredi: 2,
      thursday: 3, jeudi: 3,
      friday: 4, vendredi: 4,
      saturday: 5, samedi: 5,
      sunday: 6, dimanche: 6,
    };

    const totalSessions = (result.sessions || []).length;
    let sessionIdx = 0;
    for (const s of (result.sessions || [])) {
      sessionIdx++;
      setGenPhase(`Création des séances… (${sessionIdx}/${totalSessions})`);
      const weekOffset = ((s.week || 1) - 1) * 7;
      const normalizedDay = (s.day || '').toLowerCase().trim();
      const dayOffset = dayMap[normalizedDay] ?? 0;
      const date = addDays(monday, weekOffset + dayOffset);

      await base44.entities.Session.create({
        program_id: program.id,
        user_id: user.id,
        planned_date: format(date, 'yyyy-MM-dd'),
        estimated_duration: s.estimated_duration || 60,
        type: ['strength','hypertrophy','endurance','mixed','cardio','mobility'].includes(s.type) ? s.type : 'mixed',
        active_zones: s.active_zones || [],
        exercises: s.exercises || [],
        status: 'planned',
        week_number: s.week || 1,
        day_label: s.day_label || s.day,
      });
    }

    queryClient.invalidateQueries({ queryKey: ['programs'] });
    queryClient.invalidateQueries({ queryKey: ['program-sessions'] });

    // Snapshot des conditions de génération — permet de détecter l'obsolescence et les reverts
    const SNAPSHOT_FIELDS = ['available_days','duration_per_day','frequency_min','frequency_max','equipment','level','fragile_zones','preferred_exercises','disliked_exercises','no_volume_muscles','peaking_enabled'];
    const snapshot = {};
    SNAPSHOT_FIELDS.forEach(f => { snapshot[f] = user[f]; });
    localStorage.setItem('program_generated_snapshot', JSON.stringify(snapshot));
    localStorage.removeItem('pending_program_regen');
    setStaleBanner(false);

    } catch (err) {
      console.error('[generateProgram] erreur :', err);
      alert(`Erreur lors de la génération : ${err?.message || err}`);
    } finally {
      clearInterval(genTimerRef.current);
      setGenerating(false);
      setGenPhase('');
      setGenSeconds(0);
    }
  };

  const deleteProgram = async () => {
    if (!activeProgram) return;
    // Marquer comme completed (archiver)
    await base44.entities.Program.update(activeProgram.id, { status: 'completed' });
    // Supprimer les séances planifiées
    const planned = sessions.filter(s => s.status === 'planned');
    for (const s of planned) {
      await base44.entities.Session.delete(s.id);
    }
    queryClient.invalidateQueries({ queryKey: ['programs'] });
    queryClient.invalidateQueries({ queryKey: ['program-sessions'] });
  };

  const detectStructureType = (prog) => {
    const ws = (prog?.weekly_structure || '').toLowerCase();
    if (['full_body', 'upper_lower', 'ppl', 'arnold_split', 'custom'].includes(ws)) return ws;
    return 'unknown';
  };

  const saveProgram = async () => {
    if (!activeProgram) return;
    setSaving(true);
    const structureType = detectStructureType(activeProgram);
    const sessionTemplates = sessions.map(s => ({
      day: s.planned_date ? new Date(s.planned_date).toLocaleDateString('en', { weekday: 'long' }).toLowerCase() : '',
      day_label: s.day_label,
      week_number: s.week_number,
      type: s.type,
      estimated_duration: s.estimated_duration,
      active_zones: s.active_zones,
      exercises: s.exercises,
    }));

    const structureLabel = { full_body: 'Full Body', upper_lower: 'Upper/Lower', ppl: 'PPL', arnold_split: 'Arnold Split', custom: 'Personnalisé', unknown: '' };
    const label = structureLabel[structureType] || '';
    const actualWeeks = new Set(sessions.map(s => s.week_number).filter(Boolean)).size || activeProgram.planned_weeks || '?';
    const name = `${label ? label + ' — ' : ''}${actualWeeks} sem. · ${activeProgram.active_phase}`.trim();

    await base44.entities.SavedProgram.create({
      user_id: user.id,
      name,
      structure_type: structureType,
      weekly_structure: activeProgram.weekly_structure,
      planned_weeks: actualWeeks,
      active_phase: activeProgram.active_phase,
      multi_objective_mode: activeProgram.multi_objective_mode,
      objective_ids: activeProgram.objective_ids,
      program_data: activeProgram.program_data,
      sessions_templates: sessionTemplates,
    });

    localStorage.setItem(`saved_program_${activeProgram.id}`, 'true');
    setSaving(false);
    setSaved(true);
    setTimeout(() => setSaved(false), 3000);
  };

  // Group sessions by week
  const today = new Date();
  today.setHours(0, 0, 0, 0);

  const isPast = (session) => {
    if (!session.planned_date) return false;
    const d = new Date(session.planned_date);
    d.setHours(0, 0, 0, 0);
    return d < today;
  };

  const dayOrder = { monday: 0, lundi: 0, tuesday: 1, mardi: 1, wednesday: 2, mercredi: 2, thursday: 3, jeudi: 3, friday: 4, vendredi: 4, saturday: 5, samedi: 5, sunday: 6, dimanche: 6 };

  const weeks = {};
  sessions.forEach(s => {
    const w = s.week_number || 1;
    if (!weeks[w]) weeks[w] = [];
    weeks[w].push(s);
  });

  // Sort each week's sessions by day order
  Object.values(weeks).forEach(wSessions => {
    wSessions.sort((a, b) => {
      const dayA = (a.day_label || '').toLowerCase();
      const dayB = (b.day_label || '').toLowerCase();
      const dateA = a.planned_date ? new Date(a.planned_date).getTime() : Infinity;
      const dateB = b.planned_date ? new Date(b.planned_date).getTime() : Infinity;
      // If dates differ, sort by date; otherwise sort by day_label
      if (dateA !== dateB) return dateA - dateB;
      return (dayOrder[dayA] ?? 99) - (dayOrder[dayB] ?? 99);
    });
  });

  // Find the current week tab (first week that has a session today or in the future)
  const currentWeekTab = Object.entries(weeks).find(([, wSessions]) =>
    wSessions.some(s => !isPast(s) || s.status === 'completed')
  )?.[0] || Object.keys(weeks)[0] || '1';

  const handleRegen = () => {
    localStorage.removeItem('pending_program_regen');
    setStaleBanner(false);
    autoGenerated.current = false;
    window.location.href = '/program?autoGenerate=true';
  };

  return (
    <div className="space-y-6">
      {staleBanner && (
        <div className="flex items-center gap-2 px-3 py-2 rounded-lg bg-orange-400/10 border border-orange-400/25 text-xs text-orange-300">
          <RefreshCw className="w-3.5 h-3.5 flex-shrink-0" />
          <span className="flex-1">Programme obsolète — des paramètres de profil ont changé depuis la dernière génération.</span>
          <button onClick={handleRegen} className="font-semibold underline underline-offset-2 hover:text-orange-200 transition-colors whitespace-nowrap">Régénérer</button>
          <span className="text-orange-400/40">·</span>
          <button onClick={() => { setStaleBanner(false); localStorage.removeItem('pending_program_regen'); }} className="text-orange-300/50 hover:text-orange-300 transition-colors whitespace-nowrap">Ignorer</button>
        </div>
      )}

      <div className="flex flex-col sm:flex-row sm:items-center sm:justify-between gap-3">
        <div>
          <h1 className="text-2xl sm:text-3xl font-heading font-bold text-white">Programme</h1>
          <p className="text-white/70 mt-1 text-sm">
            {activeProgram ? `Version ${activeProgram.version} · Phase ${activeProgram.active_phase}` : ''}
          </p>
        </div>
        <div className="flex items-center gap-2">
          {activeProgram && (
            <>
              <Button variant="outline" onClick={alreadySaved ? undefined : saveProgram} disabled={saving || saved || alreadySaved} className="border-white/30 text-white hover:bg-white/10 hover:text-white">
                {alreadySaved
                  ? <><BookmarkCheck className="w-4 h-4 sm:mr-2 text-accent" /><span className="hidden sm:inline">Déjà sauvegardé</span></>
                  : saved
                  ? <><BookmarkCheck className="w-4 h-4 sm:mr-2 text-accent" /><span className="hidden sm:inline">Sauvegardé !</span></>
                  : saving
                  ? <><Loader2 className="w-4 h-4 sm:mr-2 animate-spin" /><span className="hidden sm:inline">Sauvegarde…</span></>
                  : <><Bookmark className="w-4 h-4 sm:mr-2" /><span className="hidden sm:inline">Sauvegarder</span></>
                }
              </Button>
              <AlertDialog>
                <AlertDialogTrigger asChild>
                  <Button variant="ghost" className="text-destructive hover:text-destructive hover:bg-destructive/10">
                    <Trash2 className="w-4 h-4" />
                  </Button>
                </AlertDialogTrigger>
                <AlertDialogContent>
                  <AlertDialogHeader>
                    <AlertDialogTitle>Supprimer le programme ?</AlertDialogTitle>
                    <AlertDialogDescription>
                      Toutes les séances planifiées seront supprimées. Les séances déjà complétées restent dans l'historique.
                    </AlertDialogDescription>
                  </AlertDialogHeader>
                  <AlertDialogFooter>
                    <AlertDialogCancel>Annuler</AlertDialogCancel>
                    <AlertDialogAction onClick={deleteProgram} className="bg-destructive text-destructive-foreground hover:bg-destructive/90">
                      Supprimer
                    </AlertDialogAction>
                  </AlertDialogFooter>
                </AlertDialogContent>
              </AlertDialog>
            </>
          )}
          {activeProgram && (
            <Button onClick={() => setShowRegenGate(true)} disabled={generating}>
              {generating ? <Loader2 className="w-4 h-4 sm:mr-2 animate-spin" /> : <Sparkles className="w-4 h-4 sm:mr-2" />}
              <span className="hidden sm:inline">Régénérer</span>
              <span className="sm:hidden">Régénérer</span>
            </Button>
          )}
        </div>
      </div>

      {activeProgram && Object.keys(weeks).length > 0 && (
        <Tabs defaultValue={currentWeekTab}>
          <TabsList className="bg-white/10 text-white w-full">
            {Object.keys(weeks).map(w => (
              <TabsTrigger key={w} value={w} className="flex-1 text-xs sm:text-sm">
                <span className="sm:hidden">S{w}</span>
                <span className="hidden sm:inline">Semaine {w}</span>
              </TabsTrigger>
            ))}
          </TabsList>

          {Object.entries(weeks).map(([w, weekSessions]) => (
            <TabsContent key={w} value={w}>
              <div className="grid gap-3">
                 {weekSessions.filter(session => {
                   // Cacher les séances planifiées AVANT la création du programme
                   if (session.planned_date && activeProgram?.created_at) {
                     const programStart = new Date(activeProgram.created_at);
                     programStart.setHours(0, 0, 0, 0);
                     const d = new Date(session.planned_date);
                     d.setHours(0, 0, 0, 0);
                     if (d < programStart) return false;
                   }
                   return true;
                 }).map((session, i) => {
                   const past = isPast(session) && session.status !== 'completed';
                   const sessionDate = session.planned_date ? new Date(session.planned_date) : null;
                   if (sessionDate) sessionDate.setHours(0, 0, 0, 0);
                   const isToday = sessionDate && sessionDate.getTime() === today.getTime();

                   const card = (
                     <Card className={`p-4 transition-colors bg-white/15 backdrop-blur-sm border-white/20 ${past ? 'opacity-40 cursor-not-allowed' : 'hover:bg-white/20 cursor-pointer'} ${isToday ? 'border-white/50 bg-white/25' : ''}`}>
                       <div className="flex items-center justify-between">
                         <div className="flex items-center gap-4">
                           <div className={`w-12 h-12 rounded-xl flex flex-col items-center justify-center ${isToday ? 'bg-violet-600 border-2 border-white' : 'bg-white/20'}`}>
                             <span className={`text-xs capitalize ${isToday ? 'text-white/80' : 'text-white/70'}`}>
                               {session.planned_date && format(new Date(session.planned_date), 'EEE', { locale: fr })}
                             </span>
                             <span className={`text-sm font-bold ${isToday ? 'text-white' : 'text-white'}`}>
                               {session.planned_date && format(new Date(session.planned_date), 'd')}
                             </span>
                           </div>
                           <div>
                             <div className="flex items-center gap-2 flex-wrap">
                               <span className="font-semibold text-white">{(session.day_label || '').replace(/^(week|semaine)\s*\d+\s*[-–:·]?\s*/i, '').replace(/\bmonday\b/gi, 'Lundi').replace(/\btuesday\b/gi, 'Mardi').replace(/\bwednesday\b/gi, 'Mercredi').replace(/\bthursday\b/gi, 'Jeudi').replace(/\bfriday\b/gi, 'Vendredi').replace(/\bsaturday\b/gi, 'Samedi').replace(/\bsunday\b/gi, 'Dimanche')}</span>
                               <Badge className={`bg-white/20 text-white border-white/20`}>
                                 {TYPE_LABELS[session.type] || session.type}
                               </Badge>
                               {isToday && <Badge className="text-xs bg-white/30 text-white">Aujourd'hui</Badge>}
                               {past && <Badge variant="outline" className="text-xs text-white/50 border-white/20">Passée</Badge>}
                               {session.status === 'completed' && <Badge variant="default" className="text-xs">✓ Fait</Badge>}
                             </div>
                             <div className="flex items-center gap-3 mt-1 text-xs text-white/60">
                               <span className="flex items-center gap-1"><Clock className="w-3 h-3" />{session.estimated_duration} min</span>
                               <span className="flex items-center gap-1"><Dumbbell className="w-3 h-3" />{session.exercises?.length || 0} exercices</span>
                             </div>
                           </div>
                         </div>
                         {!past && <ChevronRight className="w-5 h-5 text-white/60" />}
                       </div>
                     </Card>
                   );

                   return (
                     <motion.div
                       key={session.id}
                       initial={{ opacity: 0, y: 10 }}
                       animate={{ opacity: 1, y: 0 }}
                       transition={{ delay: i * 0.05 }}
                     >
                       {past ? card : <Link to={`/session?id=${session.id}`}>{card}</Link>}
                     </motion.div>
                   );
                 })}
              </div>
            </TabsContent>
          ))}
        </Tabs>
      )}

      {!activeProgram && !generating && (
        <Card className="p-12 text-center bg-white/15 backdrop-blur-sm border-white/20">
          <Dumbbell className="w-12 h-12 mx-auto text-white/30 mb-4" />
          <h3 className="font-heading font-bold text-xl mb-2 text-white">Pas encore de programme</h3>
          <p className="text-white/70 mb-6">L'IA va créer un programme personnalisé basé sur ton profil</p>
          <Button onClick={() => setShowDialog(true)} disabled={generating} size="lg">
            <Sparkles className="w-5 h-5 mr-2" />
            Générer mon programme
          </Button>
        </Card>
      )}
      {/* Gate régénération — si programme existant */}
      <AlertDialog open={showRegenGate} onOpenChange={setShowRegenGate}>
        <AlertDialogContent className="bg-violet-800 border-violet-700 text-white">
          <AlertDialogHeader>
            <AlertDialogTitle className="text-white">Tu as déjà un programme actif</AlertDialogTitle>
            <AlertDialogDescription className="text-white/70">
              Pour régénérer, tu dois d'abord choisir ce que tu fais avec le programme actuel.
            </AlertDialogDescription>
          </AlertDialogHeader>
          <div className="flex flex-col gap-2 py-2">
            <button
              onClick={async () => { await saveProgram(); setShowRegenGate(false); setShowDialog(true); }}
              className="flex items-center gap-3 px-4 py-3 rounded-xl bg-white/10 border border-white/20 hover:bg-white/20 transition-colors text-left"
            >
              <Bookmark className="w-5 h-5 text-violet-300 flex-shrink-0" />
              <div>
                <p className="font-semibold text-sm text-white">Sauvegarder puis régénérer</p>
                <p className="text-xs text-white/60 mt-0.5">Le programme sera conservé dans Bibliothèque avant de régénérer</p>
              </div>
            </button>
            <button
              onClick={async () => { setShowRegenGate(false); await deleteProgram(); setShowDialog(true); }}
              className="flex items-center gap-3 px-4 py-3 rounded-xl bg-red-500/20 border border-red-400/30 hover:bg-red-500/30 transition-colors text-left"
            >
              <Trash2 className="w-5 h-5 text-red-400 flex-shrink-0" />
              <div>
                <p className="font-semibold text-sm text-white">Supprimer et régénérer</p>
                <p className="text-xs text-red-300 mt-0.5">Le programme actuel sera définitivement supprimé</p>
              </div>
            </button>
          </div>
          <AlertDialogFooter>
            <AlertDialogCancel>Annuler</AlertDialogCancel>
          </AlertDialogFooter>
        </AlertDialogContent>
      </AlertDialog>

      <GenerateProgramDialog
        open={showDialog}
        onClose={() => setShowDialog(false)}
        onGenerate={generateProgram}
      />

      {generating && (
        <div className="fixed inset-0 bg-violet-900/80 backdrop-blur-sm flex flex-col items-center justify-center z-50 gap-4">
          <LoadingOrb />
          <div className="text-center space-y-1">
            <p className="text-white font-semibold text-sm">{genPhase}</p>
            <p className="text-white/50 text-xs tabular-nums">
              {(() => {
                if (genSeconds < 15)  return 'environ 1 min 30';
                if (genSeconds < 30)  return 'environ 1 min';
                if (genSeconds < 50)  return 'environ 45s';
                if (genSeconds < 65)  return 'environ 30s';
                if (genSeconds < 80)  return 'environ 15s';
                return 'finalisation…';
              })()}
            </p>
          </div>
        </div>
      )}
    </div>
  );
}